### PR TITLE
added support for hy 0.24.0 + new fallback completer

### PR DESCRIPTION
**Pull request by fergusq**
Added support for the latest release of hy and a new fallback completer. Since Jedhy doesn't support hy 0.24.0, it's still unusable.

### CODE REVIEW

**Comment by dsblank** [comment]
Thanks for this! Does the setup.py need any changes as to version or other dependencies?

**Comment by fergusq** [comment]
Other than updating the calysto_hy version number, I don't think other changes are needed. I tested it and it worked without any changes to dependencies.

The example notebooks have obsolete syntax like `(, a b)` instead of `#(a b)`. I pushed some changes to fix the other notebook, but the other would have to be copied again from the Hy tutorial.

I also changed `set_variable` and `get_variable` so that they change `self.module` and not `self.env` since module is what is given to the Hy compiler.

**Comment by dsblank** [comment]
Great! Thanks for the additional info. I'll try this out.

**Comment by actsasgeek** [comment]
At least for me, macros don't work.

Screen Shot 2022-11-30 at 11 01 18 AM

but thank you SO much for tackling this. The lack of updates to Calysto Hy has been the source of much frustration.

**Comment by fergusq** [comment]
I think you mistyped `(t [1, 2, 3])` as `t([1, 2, 3])`. It should work if you call the macro instead of just referring to its name.

**Comment by actsasgeek** [comment]
As I don't have an original version around, I'm not sure if this worked before. However, calysto hy and the hy repl give different results for evaluating expressions:

```
=> (+ '(1 2) '(kim fred))
'(1 2 kim fred)
```
versus

Screen Shot 2022-12-07 at 3 54 48 PM

Not sure if this is a "bug" with the update/revision or not... :/

**Comment by fergusq** [comment]
I don't think that was caused by my edits, but it's easily fixed. Metakernel can be configured to use a custom repr function, I should change it to use `hy.repl`.

**Comment by vrescobar** [comment]
what versions of jupyter are you using? wouldn't be bad to add a requirements.txt with their versions broken... will file a bug right now for that

**Comment by dsblank** [comment]
Could I ask one more addition: can you increment the version number? If all looks good, I'll merge. Also, if anyone is interested in helping maintain this repo, let us know!

**Comment by fergusq** [comment]
I increased the version number to 0.2.0.

**Comment by dsblank** [comment]
Thanks all!

**Pull request merged**
