### PR TITLE
May the source be with you

### PR DESCRIPTION
**Pull request by schuster-rainer**
Hello @dsblank,

here is the updated pull request for #8 , I deleted the old branch as I messed up with master and rebasing.
Please give it a final try for testing.

### CODE REVIEW

**Comment by dsblank** [comment]
Thanks! I added a bit to your patch. Please let me know if I missed anything.

**Comment by schuster-rainer** [comment]
I don't mind @dsblank just a pity that I'm not referenced as an author. But anyway I'm fine 👍

**Comment by dsblank** [comment]
My bad! My lack of git abilities. But, I will list you in a ChangeLog that is on its way.

**Comment by schuster-rainer** [comment]
Don't worry. I'm glad you merged and I could contribute something very useful, which I'm using on my own :)

**Comment by dsblank** [comment]
You're too kind! But I did get the [ChangeLog](https://github.com/Calysto/calysto_hy/blob/master/ChangeLog.md).md up with proper credits, I hope.

I'd love to get some polish on this kernel to make it even better, so if you do have additional pull requests, please feel free. Thanks again!

**Pull request closed without merging**
