### PR TITLE
Fix macro loading on Hy 0.18.0

### PR DESCRIPTION
**Pull request by reis-r**
This change updates the macro path so that it finds the macros on the newer version of Hy (0.18.0), fixing issue #15 . I really didn't get the change in load_macros but it apparently loads ok.

I also managed to get it working and evaluating, but it didn't pass some of the tests. I wonder whether the tests are outdated also (todo). There is also probably the need to clean some unused imports after the changes.

### CODE REVIEW

**Comment by dsblank** [comment]
Great! Let me know when it is ready to merge. Thanks!

**Comment by reis-r** [comment]
Everything should be working as intended now. I'll try to play with it this weekend and see if I find any bugs I can fix. You can merge it if you want.

**Comment by reis-r** [comment]
I also created a Nix recipe in case someone wants to try this out: https://gist.github.com/reis-r/244969a7ec2ad45f0b744c08a65b26e7

**Comment by s-montes** [comment]
Hey, Reis. I tried your solution and it works quite nicely. I was looking at the source code and saw a couple of minor fixes to make it run smoother. I am no expert in Hy or Jupyter kernels, but I think the can be quite useful:

**Return without lists**

```python
#### try to parse it:
        try:
            tokens = tokenize(code)
            _result = hy.eval(tokens, locals=self.env)[0]
            if _result is not None:
                self.result = _result
```

It also prevents from printing "[None]".

**Jedhy support**

```python
try:
    from jedhy.api import API as jedhy_api
    create_completer = create_jedhy_completer

(---)

def create_jedhy_completer(env):
    '''
    Return code completions from jedhy.
    '''
    jedhy = jedhy_api(globals_=env)
    def complete(txt):
        jedhy.set_namespace(globals_=env)
        return jedhy.complete(txt)
    return complete
```

**Comment by dsblank** [comment]
Is this one still needed?

**Comment by dsblank** [comment]
I'm going to close this due to lack of feedback. If someone wants to open, and handle merge conflicts, please do. Thanks!

**Pull request closed without merging**
